### PR TITLE
[Needs Review] b07902059 陳君翰

### PR DESCRIPTION
**Pull request by b07902059**
A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## What is the most challenging part in this homework?
git/ github, task5, task8
## Is this homework helpful for you?
i think so
## Is there any suggestion?
need more help, for instance, reference, lecture and more specified instructure.
<br />

### CODE REVIEW

**Comment by amjltc295** [comment]
Did you come for the TA hours for help?

**Comment by b07902059** [comment]
> Did you come for the TA hours for help?

yes, i did go to the first TA hours, but i didn't go to the second one

**Comment by amjltc295** [comment]
@b07902059 sure. You already made your submission; the merge deadline is 12/12. You could choose not to fix it as well.

**Comment by b07902059** [comment]
Urrr... i had tried my best to link the user and email account and tried to rebase some of the commits. However, none of them worked... if it is possible and needed, i would like to ask for an appointment to have further understanding regarding to this issue. thank you very much~

**Comment by amjltc295** [comment]
@b07902059  Did you force-push it to your forked repo `try3` branch? I would probably have extra TA hours today but it's not guaranteed.

**Comment by b07902059** [comment]
> @b07902059 Did you force-push it to your forked repo `try3` branch? I would probably have extra TA hours today but it's not guaranteed.

no... i didn't... 
Is it possible for me the try later? Or is this file already closed, so i can't change anything now?

**Comment by amjltc295** [comment]
The merge deadline is 12/12.

**Comment by amjltc295** [comment]
@b07902059 Add a comment in task8 would be enough.

**Comment by b07902059** [comment]
I finish adding reference for task 8!
However, I don't know why, after I link the commits to my profile (and force push it), 2 more files pop out and I have more participants. What is going on? How should I fix this?

**Comment by amjltc295** [comment]
@b07902059 Your code is from a previous commit and it's outdated now. Please see https://github.com/amjltc295/PythonHomework#update-local-and-remote-repository and rebase to the latest code.

**Comment by amjltc295** [comment]
@b07902059 Star if you like :)

**Pull request merged**
