### PR TITLE
[NeedsReview] b07902025 陳冠廷

### PR DESCRIPTION
**Pull request by timothychen1999**
A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## Is there any suggestion?

<br />

### CODE REVIEW

**Comment by amjltc295** [comment]
@timothychen1999  Why are your commit messages linked to two accounts?

**Comment by timothychen1999** [comment]
@amjltc295 I do some work on another laptop which push under another sign( it should be same account though)

**Comment by timothychen1999** [comment]
I wonder why it looks like that since my source tree also has this account as it's only github account.
Also it is the only one that can push to this repo

**Comment by amjltc295** [comment]
@timothychen1999  Obviously it's not the same account. Did you use other's laptop?  If they set up local git username and email, you could still push to your repo with HTTP authentication.

**Comment by timothychen1999** [comment]
@amjltc295 No that`s mine, but it might be the case with the fact that the ssh key for it seems not used even once

**Comment by timothychen1999** [comment]
@amjltc295  if that is the only problem, Please merge

**Pull request merged**
