### PR TITLE
[Needs Review] B07902111 張鈰瀚

### PR DESCRIPTION
**Pull request by cehann**
A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## Is there any suggestion?

<br />

### CODE REVIEW

**Comment by amjltc295** [comment]
Duplicated of #108

**Comment by cehann** [comment]
@amjltc295  teacher, sorry, what can I do when you closed this pr? I want to revise my commit message ,sorry.

**Comment by amjltc295** [comment]
@cehann you could reopen it though. Just force-push to the original forked repo (it is `undknown` now -- I don't know what have you done.)

**Comment by cehann** [comment]
@amjltc295  Because I had deleted it. I don't know what should I do, or I don't need to do anything? sorry.

**Comment by amjltc295** [comment]
@cehann in that case, you don't have to do anything for this PR. There would be some minor points deduction though. Remember that Git does not encourage changing the history (but you could always make new commits to fix them), so be careful of what you write.

However, you do have to fix your latest PR to get graded.

**Comment by cehann** [comment]
@amjltc295  Okay! I will take this lesson ,thanks!

**Pull request closed without merging**
