### PR TITLE
[Needs Review] B07902125 鄭昊昕 

### PR DESCRIPTION
**Pull request by s950449**
A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## What is the most challenging part in this homework?
Bonus. Pytest.
## Is this homework helpful for you?
Yes. Travis-CI, Pytest....
## Is there any suggestion?
No.

#78 
#90 
<br />

### CODE REVIEW

**Comment by amjltc295** [comment]
@s950449 You should not send another PR. Bad commit message would result in some minor points deduction. If you want to change it, see https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/ and https://www.git-tower.com/learn/git/faq/change-author-name-email to fix it.
You could choose not to fix it as well.

**Comment by s950449** [comment]
So I need to edit my commit in the current branch and use `git push --force` to update?

**Comment by s950449** [comment]
@amjltc295

**Comment by s950449** [comment]
Edit commit messages

**Pull request merged**
