### PR TITLE
[Needs Review] B07902117 陳漱宇

### PR DESCRIPTION
**Pull request by morrischen890717**
A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## Is there any suggestion?

<br />

### CODE REVIEW

**Comment by amjltc295** [comment]
-5 for duplicated PRs

**Comment by amjltc295** [comment]
It would be better to revise your commit message

**Comment by amjltc295** [comment]
@morrischen890717  You had deleted the original repo. I reopen the other one.

**Comment by morrischen890717** [comment]
@amjltc295 Excuse me,I can't catch your point. So what should I do next? Should I need to revise my commit message and send new PR?

**Comment by amjltc295** [comment]
@morrischen890717 At the top of this PR, the original repo is `unknown repository`. I closed this one as you could not make new changes. Please fix #151

**Comment by morrischen890717** [comment]
@amjltc295 okay, I've got it. Thanks you.

**Pull request closed without merging**
