### PR TITLE
[NeedsReview] b07902063 陳耕宇

### PR DESCRIPTION
**Pull request by Ergodica10002**
A Pull Request (PR) should explain why we need this PR and how you implement it, so others could understand it quickly.
Since this is just a homework, you do not need to explain why and how. 

**Do NOT change the status to NeedsReview if you do not want to be graded yet.**

Please fill in the following questions as feedback. It is totally optional and would not be graded.

## What is the most challenging part in this homework?
It's difficult for me to understand what 'commit' and 'pull request' mean at first. Also, this homework requires too much python learning for me.

## Is this homework helpful for you?
Yes, absolutely. It's helpful to learn how to use github and practice simple but meaningful python. 

## Is there any suggestion?
I hope TAs could teach python rather than ask us to learn by ourselves. For many students, it's the first time to access python. (though we use vpython to do general physics homework, the tools we use on physics homework is quite different from what this homework requires) 
<br />

### CODE REVIEW

**Comment by Ergodica10002** [comment]
To TA:
I asked student 李智源 for help on the homework task 8, and he taught me what the problem asked and how to do it. Since the code may be quite similar, if it is considered a plagiarism, please let me know and I'll alter my code immediately.

**Comment by amjltc295** [comment]
@Ergodica10002 The discussion is encouraged, but you have to write the code by yourself.
Your commit message is not linked to your profile. See https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/ and https://www.git-tower.com/learn/git/faq/change-author-name-email to fix it.

**Comment by Ergodica10002** [comment]
I did it myself. I just ask him for what the function and syntax means and how to use them correctly.
I' m not sure what does "commit message not linked to profile" mean. Does it mean the commit message doesn't match my commit result?

**Comment by amjltc295** [comment]
@Ergodica10002  That means the profile icon in your commit message is not linked to your github account.
screenshot from 2018-12-11 21-10-52

**Comment by amjltc295** [comment]
@Ergodica10002 By the way, thanks for your feedback. As I could not know the students' learning process without their feedback, I would like to hear more about the problems you have faced.

I did teach Python in this homework as there are lots of written code with detailed comments. The goal is to let students read, understand and modify the code by themselves and learn Python&Google in this process. I know two weeks is short, but consider most students are in the CSIE department with some previous coding experience, I think it should be achievable.

Also, if you have a better idea about the Python course, I would be glad to know:)

**Comment by Ergodica10002** [comment]
Github is pretty useful and of great importance. I'm glad that I could learn how to use it on this homework.
Besides, the instructions on the python homework did help a lot. Though I encountered many questions while doing this homework, most answers could be found on Google, and some classmates were able to help me, too. Thanks for devoting so much for us. This homework is great to me.

**Comment by amjltc295** [comment]
@Ergodica10002 Star this repo if you like it :)

**Pull request merged**
